swagger: '2.0'
info:
  title: TMS
  version: "0.1"

basePath: "/v1"

tags:
- name: UT
  description: Unit Test
- name: FT
  description: Function Test


paths:
  'RBT':
    get:
      tags: [UT]
      operationId: demo.get_it
      parameters:
        - name: resource
          in: query
          required: true
          type: string
          default: 'AfgAfg4MasterSmokeTestSuites.TestSuiteAfg4ApAlarm'
          
        - name: responder
          in: query
          required: true

          type: string
          default: 'suite'

      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"

  'Rocket':
    get:
      tags: [UT]
      operationId: demo.get_it
      parameters:
        - name: resource
          in: query
          required: true
          type: string
          default: 'AfgAfg4MasterSmokeTestSuTestSuiteAfg4ApAlarm'
          
        - name: responder
          in: query
          required: true

          type: string
          default: 'suite'

      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"





  /RBT:
    get:
      tags: [FT]
      operationId: demo.get_it
      parameters:
        - name: resource
          in: query
          required: true
          type: string
          default: 'AfgAfg4MasterSmokeTestSuites.TestSuiteAfg4ApAlarm'
          
        - name: responder
          in: query
          required: true

          type: string
          default: 'suite'

      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"

  /Rocket':
    get:
      tags: [FT]
      operationId: demo.get_it
      parameters:
        - name: resource
          in: query
          required: true
          type: string
          default: 'AfgAfg4MasterSmokeTestSuTestSuiteAfg4ApAlarm'
          
        - name: responder
          in: query
          required: true

          type: string
          default: 'suite'

      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"