swagger: '2.0'
info:
  title: FALSY SIMPLE DEMO API v2
  version: "0.2"
consumes:
  - application/json
produces:
  - application/json
basePath: "/v1"
paths:
  '/hello':
    get:
      tags: [Method]
      operationId: demo.get_it2
      summary: get
      parameters:
        - name: name
          in: query
          type: string
          default: 'john'
      responses:
        200:
          description: Return response
