swagger: '2.0'
info:
  title: TMS
  version: "0.1"
basePath: "/v1"
tags:
- name: UT
  description: Unit Test
- name: FT
  description: Function Test
- name: SFT
  description: Security Function Test 
- name: ST
  description: System test 
- name: VA
  description: Vulnerability Assessment 
- name: QA
  description: Quality Assurance
paths:
  /UT/RBT:
    get:
      tags: [UT]
      operationId: demo.get_it_TC
      parameters:
        - name: TestCaseNumber
          in: query
          required: true
          type: string
          default: '0700'
          
        - name: TestCaseName
          in: query
          required: true
          type: string
          default: 'TestCase0700SuccessAfgOpenIdConnectFeatureDisable'
        - name: Tag
          in: query
          required: true
          type: string
          default: 'AFG'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"
  /UT/Rocket:
    get:
      tags: [UT]
      operationId: demo.get_it_TS
      parameters:
        - name: TestSuiteName
          in: query
          required: true
          type: string
          default: 'TestSuiteVafgEnafGba'
          
        - name: Tag
          in: query
          required: true
          type: string
          default: 'AFG'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"
  /FT/RBT:
    get:
      tags: [FT]
      operationId: demo.get_it_TC
      parameters:
        - name: TestCaseNumber
          in: query
          required: true
          type: string
          default: 60
          
        - name: TestCaseName
          in: query
          required: true
          type: string
          default: 'AfgOfflineLicenseTestSuites'
        - name: Tag
          in: query
          required: true
          type: string
          default: 'AFG'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"
  /FT/Rocket:
    get:
      tags: [FT]
      operationId: demo.get_it_TS
      parameters:
        - name: TestSuiteName
          in: query
          required: true
          type: string
          default: 'AfgAfg4MasterSmokeTestSuTestSuiteAfg4ApAlarm'
          
        - name: Tag
          in: query
          required: true
          type: string
          default: 'suite'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"
  /SFT/RBT:
    get:
      tags: [SFT]
      operationId: demo.get_it_TC
      parameters:
        - name: TestCaseNumber
          in: query
          required: true
          type: string
          default: 60
          
        - name: TestCaseName
          in: query
          required: true
          type: string
          default: 'AfgOfflineLicenseTestSuites'
        - name: Tag
          in: query
          required: true
          type: string
          default: 'AFG'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"
  /ST/RBT:
    get:
      tags: [ST]
      operationId: demo.get_it_TC
      parameters:
        - name: TestCaseNumber
          in: query
          required: true
          type: string
          default: 60
          
        - name: TestCaseName
          in: query
          required: true
          type: string
          default: 'AfgOfflineLicenseTestSuites'
        - name: Tag
          in: query
          required: true
          type: string
          default: 'AFG'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"
  /VA/RBT:
    get:
      tags: [VA]
      operationId: demo.get_it_TC
      parameters:
        - name: TestCaseNumber
          in: query
          required: true
          type: string
          default: 60
          
        - name: TestCaseName
          in: query
          required: true
          type: string
          default: 'AfgOfflineLicenseTestSuites'
        - name: Tag
          in: query
          required: true
          type: string
          default: 'AFG'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"
  /QA/RBT:
    get:
      tags: [QA]
      operationId: demo.get_it_TC
      parameters:
        - name: TestCaseNumber
          in: query
          required: true
          type: string
          default: 60
          
        - name: TestCaseName
          in: query
          required: true
          type: string
          default: 'AfgOfflineLicenseTestSuites'
        - name: Tag
          in: query
          required: true
          type: string
          default: 'AFG'
      responses:
        200:
          description: Return response
      produces:
        - "application/xml"
        - "application/json"